[package]
name = "boss_time_estimate"
version = "0.1.0"
authors = ["Typas Liao <typascake@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
lazy_static = "1.4"
rayon = "1.5"
